# -*- coding: utf-8 -*-
"""irrigation_method_recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hOTlybDSrlW-zZYZztW87o7t1CybrwL
"""

import streamlit as st
import pandas as pd
from collections import defaultdict
from Utils import load_model, load_related_data, get_info

st.set_page_config(
    page_title="Irrigation Method Recommendation Tool",
    page_icon="💧",
    layout="wide"
)

st.markdown(
    f"""
    <style>
    .stApp {{
        background: linear-gradient(rgba(255, 255, 255, 0.85), rgba(255, 255, 255, 0.3)), 
                    url("https://png.pngtree.com/thumb_back/fw800/background/20251102/pngtree-center-pivot-irrigation-in-a-field-at-sunset-light-image_20201383.webp");
        background-attachment: scroll;
        background-size: cover;
    }}

    .element-container:has(#results-anchor) {{
        background-color: transparent !important;
    }}

    div[data-testid="stVerticalBlock"]:has(> div #results-anchor) {{
        background-color: white !important;
        padding: 40px !important;
        border-radius: 15px !important;
        box-shadow: 0 10px 25px rgba(0,0,0,0.2) !important;
        margin-top: 20px !important;
        border: 1px solid #eee !important;
    }}

    [data-testid="stForm"] {{
        background-color: white !important;
        padding: 30px !important;
        border-radius: 15px !important;
    }}
    [data-testid="stAppViewContainer"] {{
        background-color: rgba(0,0,0,0); /* Make sure the container is transparent */
    }}
    </style>
    """,
    unsafe_allow_html=True
)

CAT_COLUMNS = ["plant_type_standardized_to_10", "irrigation_scheduling_method_standardized", "soil_type_standardized"]
NUMERIC_COLUMNS = ["latitude_decimal_degrees", "longitude_decimal_degrees", "altitude_numeric"]
METHOD_LABEL = ["Conventional/Fixed Scheduling", "Deficit/Partial Irrigation", "Evapotranspiration-Based",
                "Soil Moisture-Based", "Plant or Climate-Based"
    , "Specialized Irrigation Delivery"]
METHOD_LABEL.sort()

if 'page' not in st.session_state:
    st.session_state.page = 'home'

if st.session_state.page == 'home':

    st.markdown("""
    <style>
        .stTextInput>div>div>input, .stNumberInput>div>div>input, .stSelectbox>div>div>div {
            border: 2px solid #2e8b57;
            border-radius: 5px;
        }
        .stButton>button {
            background-color: #2e8b57;
            color: white;
            font-weight: bold;
            width: 100%;
            padding: 0.5rem;
            border-radius: 5px;
        }
        .stButton>button:hover {
            background-color: #3c763d;
        }
    </style>
    """, unsafe_allow_html=True)

    st.markdown(
        """
        <p style="font-size:30px;">
            Please click <a href="https://sites.google.com/view/irrigationmatch/home">this link</a> 
            to view the full website.
        </p>
        """,
        unsafe_allow_html=True
    )
    # Page title
    st.markdown("""
    <h1 style='text-align: center; color: #2e8b57;'>
        <img src="logo.png" style="width:40px; vertical-align: middle; margin-right:10px;">
        Irrigation Method Recommendation Tool
    </h1>
    """, unsafe_allow_html=True)

    with st.form("irrigation_form"):
        st.markdown("### Location Information")
        st.markdown("""
        <div style="display: flex; align-items: left; margin-bottom: 3px;">
            <span style="font-size: 20px; margin-right: 5px">Find your Lat/lon from your address</span>
            <a href="https://www.latlong.net/" 
               target="_blank" 
               title="Latlong" 
               style="text-decoration: none; color: #2e8b57; cursor: pointer">
               ⓘ
            </a>
        </div>
        """, unsafe_allow_html=True)

        # Create two columns for better layout
        col1, col2, col3 = st.columns(3)

        with col1:
            st.number_input(
                "Latitude (decimal degrees)",
                min_value=-90.0,
                max_value=90.0,
                value=0.0,
                step=1.0,
                format="%.3f",
                key='latitude'
            )

        with col2:
            st.number_input(
                "Longitude (decimal degrees)",
                min_value=-180.0,
                max_value=180.0,
                value=0.0,
                step=1.0,
                format="%.3f",
                key='longitude'
            )

        with col3:
            st.markdown("""
                <div style="display: flex; align-items: center; margin-bottom: 3px;">
                    <span style="font-size: 14px; margin-right: 5px">Altitude (meters above sea level)</span>
                    <a href="https://www.mapdevelopers.com/elevation_calculator.php" 
                       target="_blank" 
                       title="View Altitude" 
                       style="text-decoration: none; color: #2e8b57; cursor: pointer">
                       ⓘ
                    </a>
                </div>
                """, unsafe_allow_html=True)
            st.number_input(
                "Altitude (meters above sea level)",
                min_value=0.0,  # Dead Sea is about -430m
                max_value=9000.0,  # Mount Everest is about 8848m
                value=0.0,
                step=1.0,
                format="%.1f",
                key='altitude',
                label_visibility="collapsed"
            )

        st.markdown("### Crop Information")

        # Soil type and plant type in the same row
        col4, col5 = st.columns(2)
        with col4:
            st.markdown("""
                <div style="display: flex; align-items: center; margin-bottom: 3px;">
                    <span style="font-size: 14px; margin-right: 5px">Soil Type</span>
                    <a href="https://www.nano-yield.com/the-soil-texture-triangle" 
                       target="_blank" 
                       title="View USDA Soil Texture Chart" 
                       style="text-decoration: none; color: #2e8b57; cursor: pointer">
                       ⓘ
                    </a>
                </div>
                """, unsafe_allow_html=True)
            st.selectbox("",
                         ['coarse sands', 'fine sands', 'loamy sands', 'sandy loams', 'fine sandy loams', 'silt loams',
                          'silty clay loams', 'silty clay', 'clay'],
                         key="soil_type", label_visibility="collapsed"
                         )

        with col5:
            st.selectbox(
                "Plant Type",
                ["Wheat", "Maize", "Soybean", "Legumes_Grains", "Vegetables", "Hay", "Fibers_Oilseeds", "Perennials",
                 "Root_Tubers", "Vines"],
                key="plant_type"
            )

        st.selectbox("Model Type (Sorted by accuracy (highest to lowest))",
                     ["XGBoost_Model (Recommended)", "GradientBoosting", "RandomForest", "ExtraTrees",
                      "DecisionTree", "KNN", "MLP", "AdaBoost", "Ridge", "Lasso", "SVR"],
                     key="model_type")


        def go_to_results():
            st.session_state.page = 'results'


        submit_button = st.form_submit_button("Get Irrigation Recommendation", on_click=go_to_results)

elif st.session_state.page == 'results':
    if st.button("Back"):
        st.session_state.page = 'home'
        st.rerun()
    with st.container(border=True):
        st.markdown('<div id="results-anchor"></div>', unsafe_allow_html=True)

        latitude = st.session_state.latitude
        longitude = st.session_state.longitude
        altitude = st.session_state.altitude
        soil_type = st.session_state.soil_type
        plant_type = st.session_state.plant_type
        model_type = st.session_state.model_type

        # Display the input values (for demonstration)
        with st.expander("View Input Parameters"):
            st.write(f"- Latitude: {latitude}°")
            st.write(f"- Longitude: {longitude}°")
            st.write(f"- Altitude: {altitude} meters")
            st.write(f"- Soil Type: {soil_type}")
            st.write(f"- Plant Type: {plant_type}")

        st.success("Based on the above input parameters you provided, here are the top two recommended irrigation scheduling methods for your farm!")

        user_input = defaultdict(list)
        for method in METHOD_LABEL:
            user_input[CAT_COLUMNS[0]].append(plant_type)
            user_input[CAT_COLUMNS[1]].append(method)
            user_input[CAT_COLUMNS[2]].append(soil_type)
            user_input[NUMERIC_COLUMNS[0]].append(latitude)
            user_input[NUMERIC_COLUMNS[1]].append(longitude)
            user_input[NUMERIC_COLUMNS[2]].append(altitude)

        user_dict = pd.DataFrame(user_input)

        if model_type == "XGBoost_Model (Recommended)":
            model_type = "XGBoost_Model"
        model = load_model(model_type)
        predictions = model.predict(user_dict)

        irrigation_method_yield = dict(
            zip(METHOD_LABEL, predictions)
        )

        # sort the dictionary based on the yield
        sorted_irrigation_method_yield = dict(sorted(irrigation_method_yield.items(), key=lambda x: x[1], reverse=True))
        # select the best first two options
        best_two_options = list(sorted_irrigation_method_yield.keys())[:2]

        st.markdown(f"### 🌟 Recommended Irrigation Method - {best_two_options[0]}")

        summary, resources = get_info(best_two_options[0])

        with st.expander(f"**What is {best_two_options[0]} Irrigation Scheduling?**"):
            st.info(summary)

        with st.expander(f"**Helpful Links to Setup {best_two_options[0]} Irrigation Scheduling**"):
            st.info(resources)

        with st.expander(f"**Most Related Research Paper in Dataset:**"):
            most_related_row, link, conditions_summary, setup_params, method_params = load_related_data(user_dict,
                                                                                                        best_two_options[
                                                                                                            0])
            if isinstance(most_related_row, int):
                st.info("""No related data found""")
            else:
                st.info("""Source row from dataset""")
                st.info(f"""★ ≈**{(most_related_row["distance"] * 0.5) * 111.320}** kilometers away from your farm ★""")
                st.dataframe(most_related_row)

                with st.expander("More details about irrigation scheduling method"):
                    if isinstance(method_params, str) and method_params.strip():
                        for key, value in eval(method_params).items():
                            st.write(f"* **{key}:** {value}")
                    else:
                        st.write("No parameters available.")

                with st.expander("Experimental Setup Details"):
                    if isinstance(setup_params, str) and setup_params.strip():
                        for key, value in eval(setup_params).items():
                            st.write(f"* **{key}:** {value}")
                    else:
                        st.write("No parameters available.")

                st.link_button("**==> Click this to read more of this paper**", link)

        st.markdown(f"### 🌟 2nd Best Irrigation Method - {best_two_options[1]}")

        summary, resources = get_info(best_two_options[1])

        with st.expander(f"**What is {best_two_options[1]} Irrigation Scheduling?**"):
            st.info(summary)

        with st.expander(f"**Helpful Links to Setup {best_two_options[1]} Irrigation Scheduling**"):
            st.info(resources)

        with st.expander(f"**Most Related Research Paper in Dataset:**"):
            most_related_row, link, conditions_summary, setup_params, method_params = load_related_data(user_dict,
                                                                                                        best_two_options[
                                                                                                            1])
            if isinstance(most_related_row, int):
                st.info("""No related data found""")
            else:
                st.info("""Source row from dataset""")
                st.info(f"""★ ≈**{(most_related_row["distance"] * 0.5) * 111.320}** kilometers away from your farm ★""")
                st.dataframe(most_related_row)

                with st.expander("More details about irrigation scheduling method"):
                    if isinstance(method_params, str) and method_params.strip():
                        for key, value in eval(method_params).items():
                            st.write(f"* **{key}:** {value}")
                    else:
                        st.write("No parameters available.")

                with st.expander("Experimental Setup Details"):
                    if isinstance(setup_params, str) and setup_params.strip():
                        for key, value in eval(setup_params).items():
                            st.write(f"* **{key}:** {value}")
                    else:
                        st.write("No parameters available.")

                st.link_button("**==> Click this to read more of this paper**", link)
