# -*- coding: utf-8 -*-
"""home_page.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZ3CTBUTTkEDkOuMMUuzSZdcNLqAjYxI
"""

import streamlit as st

st.set_page_config(
    page_title="Smart Irrigation Predictor",
    page_icon="💧",
    layout="centered"
)

st.markdown("""
<style>
    .main-header {color: #2e8b57; text-align: center; padding: 2rem 0;}
    .description {text-align: center; font-size: 1.2rem; color: #3c763d;}
</style>
""", unsafe_allow_html=True)

st.markdown("<h1 class='main-header'>🌱 Smart Irrigation Prediction System</h1>", unsafe_allow_html=True)
st.markdown("""
<p class='description'>
    Welcome to our Smart Irrigation Prediction System.
    This application helps farmers optimize their irrigation practices for maximum crop yield.
</p>
""", unsafe_allow_html=True)