# -*- coding: utf-8 -*-
"""irrigation_method_recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19hOTlybDSrlW-zZYZztW87o7t1CybrwL
"""

import streamlit as st
import pandas as pd
from collections import defaultdict
from Utils import load_pickle_files

CAT_COLUMNS = ["plant_type_standardized_to_6", "method_label"]
NUMERIC_COLUMNS  = ["latitude_decimal_degrees", "longitude_decimal_degrees", "altitude_numeric", "water_productivity_kg_per_m^3"]
METHOD_LABEL = ["Conventional/Fixed scheduling", "Deficit/Partial irrigation", "Evapotranspiration-based", "Soil-moisture-based", "Plant- or climate-based"]

METHOD_LABEL.sort()

onehot_encoder = load_pickle_files(encoder)
standard_scaler = load_pickle_files(scaler)
model = load_pickle_files(rf_model)

st.set_page_config(
    page_title="Irrigation Method Recommendation",
    page_icon="💧",
    layout="centered"
)

st.markdown("""
<style>
    .stTextInput>div>div>input, .stNumberInput>div>div>input, .stSelectbox>div>div>div {
        border: 2px solid #2e8b57;
        border-radius: 5px;
    }
    .stButton>button {
        background-color: #2e8b57;
        color: white;
        font-weight: bold;
        width: 100%;
        padding: 0.5rem;
        border-radius: 5px;
    }
    .stButton>button:hover {
        background-color: #3c763d;
    }
</style>
""", unsafe_allow_html=True)

# Page title
st.markdown("<h1 style='text-align: center; color: #2e8b57;'>🌱 Irrigation Method Recommendation</h1>", unsafe_allow_html=True)

with st.form("irrigation_form"):
    st.markdown("### Location Information")

    # Create two columns for better layout
    col1, col2, col3 = st.columns(3)

    with col1:
        latitude = st.number_input(
            "Latitude (decimal degrees)",
            min_value=-90.0,
            max_value=90.0,
            value=0.0,
            step=0.000001,
            format="%.6f"
        )

    with col2:
        longitude = st.number_input(
            "Longitude (decimal degrees)",
            min_value=-180.0,
            max_value=180.0,
            value=0.0,
            step=0.000001,
            format="%.6f"
        )

    with col3:
        altitude = st.number_input(
            "Altitude (meters above sea level)",
            min_value=0.0,  # Dead Sea is about -430m
            max_value=9000.0,  # Mount Everest is about 8848m
            value=0.0,
            step=0.1,
            format="%.1f"
        )

    st.markdown("### Crop Information")

    # Water productivity and plant type in the same row
    col4, col5 = st.columns(2)
    with col4:
        water_productivity = st.number_input(
            "Water Productivity (kg/m³)",
            min_value=0.0,
            max_value=100.0,
            value=1.0,
            step=0.1,
            format="%.2f"
        )

    with col5:
        plant_type = st.selectbox(
            "Plant Type",
            ["Vegetables", "Grains", "Fruits", "Oil / Fiber / Industrial Crops", "Legumes"]
        )

    # Submit button
    submit_button = st.form_submit_button("Get Irrigation Recommendation")
if submit_button:
    st.success("Form submitted successfully!")

    # Display the input values (for demonstration)
    with st.expander("View Input Parameters"):
        st.write(f"- Latitude: {latitude}°")
        st.write(f"- Longitude: {longitude}°")
        st.write(f"- Altitude: {altitude} meters")
        st.write(f"- Water Productivity: {water_productivity} kg/m³")
        st.write(f"- Plant Type: {plant_type}")

    user_input = defaultdict(list)
    for method in METHOD_LABEL:
        user_input[CAT_COLUMNS[0]].append(plant_type)
        user_input[CAT_COLUMNS[1]].append(method)
        user_input[NUMERIC_COLUMNS[0]].append(latitude)
        user_input[NUMERIC_COLUMNS[1]].append(longitude)
        user_input[NUMERIC_COLUMNS[2]].append(altitude)
        user_input[NUMERIC_COLUMNS[3]].append(water_productivity)

    user_dict = pd.DataFrame(user_input)
    # encode the categorical columns
    ohe_labels = onehot_encoder.get_feature_names_out(CAT_COLUMNS)
    cat_data = onehot_encoder.transform(user_dict[CAT_COLUMNS])
    cat_df = pd.DataFrame(cat_data, columns=ohe_labels)
    # drop the columns from the user dataframe
    user_dict.drop(CAT_COLUMNS, axis=1, inplace=True)
    # concat the user dataframe and the encoded dataframe
    user_dict = pd.concat([cat_df, user_dict], axis=1)
    # scale the numeric columns
    user_dict[NUMERIC_COLUMNS] = standard_scaler.transform(user_dict[NUMERIC_COLUMNS])
    user_dict_array = user_dict.values
    # loop through each row and predict the irrigation method
    irrigation_method_yield = {}

    for index, row in enumerate(user_dict_array):
      plant_yield = model.predict([row])[0]
      irrigation_method_yield[METHOD_LABEL[index]] = plant_yield

    # sort the dictionary based on the yield
    sorted_irrigation_method_yield = dict(sorted(irrigation_method_yield.items(), key=lambda x: x[1], reverse=True))
    # select the best first two options
    best_two_options = list(sorted_irrigation_method_yield.keys())[:2]

    st.markdown("### 🌟 Recommended Irrigation Method")
    st.info(f"""
    **The best irrigation method for your location is {best_two_options[0]}**

    Based on your inputs, **{best_two_options[0]}** is recommended for optimal water efficiency and crop yield.
    This method is particularly effective for your selected plant type and location.

    **The second best irrigation method for your location is {best_two_options[1]}**

    Based on your inputs, **{best_two_options[1]}** is the second best option recommended for optimal water efficiency and crop yield.
    This method is particularly effective for your selected plant type and location.
    """)
